### ISSUE TITLE
tried to assembled

### ISSUE THREAD

**Issue by tycs03** [bouletmarc/BMBurner#1]
tried to assemble the burner can't get it to work. don't really know whats wrong. also can i ask is Q1 and Q2  emitter connected to ground ? i try the circuit and nothing happens when i try to blank check software says its not blank. but its a new chip. when i try to write software says write ok but when verify buffer not the same.  

please  help 

thanks

**Comment by tycs03** [comment]
ok so i have done further testing, i found that my transistors were installed incorrectly Q1 and Q2. after rectifying that, i have tested the programmer and found that it does not work with 29c256. however it does work with 27sf512. I hope this issue could be fixed as i have built this programmer mainly for atmel 29c256

tested with a new atmel 29c256 when trying to check blank software says 'ITS NOT BLANK' when try to write software says " WRITE SUCCESS" when i try to verify " BUFFER DOES NOT MATCH" when i try to read the chip is indeed blank. 

tried the atmel 29c256 on a friend universal progrmmer and the chip is good. 

thank you

**Comment by bouletmarc** [comment]
this project was mainly done for 27SF512 and Im not working on it anymore, well atleast for now, It might get updated one day, but now the development are kinda stopped
