### ISSUE TITLE
Unable to erase W27C512

### ISSUE THREAD

**Issue by StormTrooper** [bouletmarc/BMBurner#2]
I''m using the latest version of bmburner and I think I found a bug. 

Selecting W27c512 and select erase chip. It does through the motions and says chip is erased but when I blank check the chip, its not black.

If however  I run arduino and send 5ECS through the console then the chip is successfully blanked. 

Are you able to reproduce this issue?

**Comment by bouletmarc** [comment]
the new BMBurner can now do W27C512
