### ISSUE TITLE
Why the 27C512 etc chips are read-only with BMBurner?

### ISSUE THREAD

**Issue by iddq** [bouletmarc/BMBurner#3]

**Comment by StormTrooper** [comment]
Not sure about the 27C512 but the circuit does not cater for programming the 27C256

**Comment by bouletmarc** [comment]
the circuit of the BMBurner doesn't allow that, it require 6.5V on the VCC pin and 12.5V on the VPP pin to program a 27C256 chip, it may eventually exist in a next revision
